# Generated by Django 3.0.8 on 2020-08-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoSin',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('din_solicitacao', models.DateTimeField(null=True)),
                ('dsc_manutencao', models.TextField()),
                ('tip_supervisao', models.CharField(choices=[('SIM', 'Supervisionado'), ('NAO', 'Sem Supervisao'), ('NDA', 'Nao Avaliado')], default='NDA', max_length=3)),
                ('pct_supervisao', models.CharField(max_length=10, null=True)),
                ('din_execucao', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoSin',
            fields=[
                ('num_dia', models.IntegerField(primary_key=True, serialize=False)),
                ('tip_supervisao', models.CharField(max_length=3)),
                ('num_quantidade', models.IntegerField()),
            ],
        ),
    ]
