# Generated by Django 3.0.8 on 2020-08-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [       
        migrations.CreateModel(
            name='DadosEstatistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('dsc_predicao', models.CharField(max_length=20, null=True)),
                ('qtd_registro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DadosPredicao',
            fields=[
                ('id_sin', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dsc_texto', models.TextField(null=True)),
                ('tip_supervisao', models.CharField(max_length=5, null=True)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('tip_evento', models.CharField(max_length=5, null=True)),
                ('tip_predicao', models.CharField(max_length=5, null=True)),
                ('pct_predicao', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosRetreino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sin', models.CharField(max_length=30, null=True)),
                ('dsc_texto', models.TextField(null=True)),
                ('tip_supervisao', models.CharField(max_length=5, null=True)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('tip_evento', models.CharField(max_length=5, null=True)),
                ('tip_predicao', models.CharField(max_length=5, null=True)),
                ('pct_predicao', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosColeta',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('din_evento', models.DateTimeField(null=True)),
                ('dsc_manutencao', models.TextField()),
                ('tip_evento', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
