# Generated by Django 3.0.8 on 2020-08-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadosin',
            options={'managed': False},
        ),
    ]
