# Generated by Django 3.0.8 on 2020-09-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coleta',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('din_evento', models.DateTimeField(null=True)),
                ('dsc_manutencao', models.TextField()),
            ],
        ),
    ]
