# Generated by Django 3.0.8 on 2020-08-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200825_0022'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resultadosin',
            table='applications_ResultadoSin',
        ),
    ]
