# Generated by Django 3.0.8 on 2020-09-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_coleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='estatistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('dsc_predicao', models.CharField(max_length=20, null=True)),
                ('qtd_registro', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='predicao',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dsc_texto', models.TextField(null=True)),
                ('tip_supervisao', models.CharField(max_length=5, null=True)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('tip_legenda', models.CharField(max_length=10, null=True)),
                ('tip_predicao', models.CharField(max_length=5, null=True)),
                ('pct_predicao', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='treinoteste',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dsc_texto', models.TextField(null=True)),
                ('tip_legenda', models.CharField(max_length=10, null=True)),
                ('tip_predicao', models.CharField(max_length=5, null=True)),
                ('pct_predicao', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
