# Generated by Django 3.0.8 on 2020-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_estatistica_predicao_treinoteste'),
    ]

    operations = [
        migrations.CreateModel(
            name='coletatestetreino',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('din_evento', models.DateTimeField(null=True)),
                ('dsc_texto', models.TextField(null=True)),
                ('tip_supervisao', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='dsc_manutencao',
        ),
        migrations.AddField(
            model_name='coleta',
            name='dsc_texto',
            field=models.TextField(null=True),
        ),
    ]
