# Generated by Django 3.0.8 on 2020-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200825_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumosin',
            name='tip_origemsupervisao',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
