# Generated by Django 3.0.8 on 2020-09-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20200910_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinoteste',
            name='din_calculo',
            field=models.DateTimeField(null=True),
        ),
    ]
