# Generated by Django 3.0.8 on 2020-09-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_insumosgi_resultadosgi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insumosgi',
        ),
        migrations.DeleteModel(
            name='ResultadoSgi',
        ),
    ]
