# Generated by Django 3.0.8 on 2020-09-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_treinoteste_din_calculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicao',
            name='tip_legenda',
        ),
    ]
