# Generated by Django 3.0.8 on 2020-09-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_predicao_tip_legenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatistica',
            name='tip_legenda',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
