# Generated by Django 3.0.8 on 2020-09-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_estatistica_tip_legenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicao',
            name='val_realpredicao',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
