# Generated by Django 3.0.8 on 2020-09-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20200831_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumosin',
            name='pct_supervisao',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
