# Generated by Django 3.0.8 on 2020-09-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20200831_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumosin',
            name='tip_supervisao',
            field=models.CharField(choices=[('sim', 'Supervisionado'), ('nao', 'Sem Supervisao'), ('nda', 'Nao Avaliado')], default='nda', max_length=3, null=True),
        ),
    ]
