# Generated by Django 3.0.8 on 2020-09-01 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20200901_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumosin',
            old_name='tip_origemsupervisao',
            new_name='tip_supresult',
        ),
    ]
