# Generated by Django 3.0.8 on 2020-09-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20200901_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosColeta',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('din_evento', models.DateTimeField(null=True)),
                ('dsc_manutencao', models.TextField()),
                ('tip_evento', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosGroup',
            fields=[
                ('din_execucao', models.DateTimeField(primary_key=True, serialize=False)),
                ('tot_oper', models.IntegerField()),
                ('tot_prop', models.IntegerField()),
                ('tot_registro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DadosResultado',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('din_evento', models.DateTimeField(null=True)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('tip_evento', models.CharField(max_length=5, null=True)),
                ('tip_predicao', models.CharField(max_length=5, null=True)),
                ('pct_predicao', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosTreinoTeste',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('din_evento', models.DateTimeField(null=True)),
                ('dsc_manutencao', models.TextField()),
                ('tip_supervisao', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='insumosin',
            name='tip_supervisao',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
