# Generated by Django 3.0.8 on 2020-09-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20200904_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadostreinoteste',
            name='din_evento',
        ),
        migrations.AlterField(
            model_name='dadostreinoteste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
