# Generated by Django 3.0.8 on 2020-09-05 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20200904_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosresultado',
            name='din_evento',
        ),
        migrations.AddField(
            model_name='dadosresultado',
            name='idsin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dadosresultado',
            name='din_execucao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dadosresultado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
