# Generated by Django 3.0.8 on 2020-09-05 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20200904_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_texto', models.TextField(null=True)),
                ('din_execucao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pct_predicao', models.CharField(max_length=10, null=True)),
                ('tip_predicao', models.CharField(max_length=5, null=True)),
                ('tip_evento', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DadosResultado',
        ),
    ]
