# Generated by Django 3.0.8 on 2020-09-05 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20200904_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosresult',
            name='din_execucao',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
