# Generated by Django 3.0.8 on 2020-09-05 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20200904_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosresult',
            name='din_execucao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
