# Generated by Django 3.0.8 on 2020-09-05 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20200904_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosresult',
            name='din_execucao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
