# Generated by Django 3.0.8 on 2020-09-05 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_auto_20200904_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosresult',
            name='din_execucao',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 23, 39, 39, 88711)),
        ),
    ]
