# Generated by Django 3.0.8 on 2020-09-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20200904_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosResultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_texto', models.TextField(null=True)),
                ('tip_evento', models.CharField(max_length=5, null=True)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('tip_predicao', models.CharField(max_length=5, null=True)),
                ('pct_predicao', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DadosResult',
        ),
    ]
