# Generated by Django 3.0.8 on 2020-09-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20200904_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosTreinoTeste',
        ),
    ]
