# Generated by Django 3.0.8 on 2020-09-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_dadosretreino'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAvaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('tip_evento', models.CharField(max_length=5, null=True)),
                ('tip_predicao', models.CharField(max_length=5, null=True)),
                ('qtd_registro', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DadosGroup',
        ),
        migrations.DeleteModel(
            name='DadosResultado',
        ),
    ]
