# Generated by Django 3.0.8 on 2020-09-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_auto_20200905_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsumoSin',
        ),
        migrations.DeleteModel(
            name='ResultadoSin',
        ),
    ]
