# Generated by Django 3.0.8 on 2020-09-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_dadospredicao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosPredicao',
        ),
    ]
