# Generated by Django 3.0.8 on 2020-09-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_delete_dadospredicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPredicao',
            fields=[
                ('id_sin', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dsc_texto', models.TextField(null=True)),
                ('tip_supervisao', models.CharField(max_length=5, null=True)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('tip_evento', models.CharField(max_length=5, null=True)),
                ('tip_predicao', models.CharField(max_length=5, null=True)),
                ('pct_predicao', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
