# Generated by Django 3.0.8 on 2020-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_dadospredicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEstatistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('din_execucao', models.DateTimeField(null=True)),
                ('dsc_predicao', models.CharField(max_length=20, null=True)),
                ('qtd_registro', models.IntegerField()),
            ],
        ),
    ]
