# Generated by Django 3.0.8 on 2020-09-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_dadosestatistica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosAvaliacao',
        ),
    ]
