# Generated by Django 3.1 on 2020-09-11 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='fbprophet', max_length=50)),
                ('train_initial_date', models.DateTimeField()),
                ('train_last_date', models.DateTimeField()),
                ('test_score', models.FloatField(default=0)),
                ('test_accuracy', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('name', 'train_initial_date', 'train_last_date')},
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(unique=True)),
                ('PJME_MW', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Forecasts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PJME_MW', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('error', models.FloatField(default=0)),
                ('percentage_error', models.FloatField(default=0)),
                ('forecast_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.forecastmodels')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.measurements')),
            ],
        ),
    ]
