# Generated by Django 3.0.8 on 2020-08-03 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
            ],
            options={
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='ForecastModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='fbprophet', max_length=50)),
                ('train_last_date', models.DateField()),
                ('test_score', models.FloatField(default=0.0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.Countries')),
            ],
            options={
                'unique_together': {('name', 'train_last_date', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cases', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.Countries')),
            ],
            options={
                'unique_together': {('date', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Forecasts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estimated_cases', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('error', models.FloatField(default=0)),
                ('forecast_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.ForecastModels')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.Measurements')),
            ],
            options={
                'unique_together': {('forecast_model', 'date')},
            },
        ),
    ]
