# Generated by Django 3.0.8 on 2020-08-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_forecastmodels_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastmodels',
            name='status',
        ),
    ]
