# Generated by Django 3.0.8 on 2020-08-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_remove_forecastmodels_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmodels',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
