# Generated by Django 3.0.8 on 2020-08-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_forecastmodels_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='deaths',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurements',
            name='recovered',
            field=models.FloatField(default=0),
        ),
    ]
