# Generated by Django 3.0.8 on 2020-08-04 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_auto_20200803_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmodels',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='forecast.Countries'),
        ),
    ]
