# Generated by Django 3.0.8 on 2020-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_auto_20200803_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmodels',
            name='test_accuracy',
            field=models.FloatField(default=0),
        ),
    ]
