# Generated by Django 3.0.8 on 2020-08-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('fixed_acidity', models.FloatField()),
                ('volatile_acidity', models.FloatField()),
                ('citric_acidity', models.FloatField()),
                ('residual_sugar', models.FloatField()),
                ('chlorides', models.FloatField()),
                ('free_sulfur_dioxide', models.FloatField()),
                ('total_sulfur_dioxide', models.FloatField()),
                ('density', models.FloatField()),
                ('pH', models.FloatField()),
                ('sulphates', models.FloatField()),
                ('alcohol', models.FloatField()),
                ('estimated_score', models.FloatField()),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='SupplierMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Supplier')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Wine')),
            ],
            options={
                'ordering': ['supplier', 'created'],
                'unique_together': {('wine', 'supplier')},
            },
        ),
    ]
