# Generated by Django 3.0.8 on 2020-08-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='citric_acidity',
            new_name='citric_acid',
        ),
    ]
