# Generated by Django 3.0.8 on 2020-08-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_auto_20200811_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='estimated_score',
            field=models.FloatField(null=True),
        ),
    ]
